# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanArchitecture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 4.0'
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  # Pods for CleanArchitecture

  target 'CleanArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanArchitectureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
